config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'user/registrations'
  }

  root 'staticpage#index'

  resources :buckets do
    resources :lists
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bucket.rb
class Bucket < ApplicationRecord
  has_many :lists, dependent: :destroy

  belongs_to :user
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :bucket

  def self.category
    ['Adventure', 'Service', 'Family', 'Make', 'Read', 'Visit']
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :buckets, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController

  def index
    @buckets = Bucket.where(user_id:current_user.id)
  end

  def show
    @bucket = Bucket.find(params[:id])
  end

  def new
    @bucket = Bucket.new
  end

  def create
    @bucket = Bucket.new(bucket_params)
    @bucket.user_id = current_user.id
    if @bucket.save
      redirect_to bucket_path(@bucket)
    else
      render :new
    end
  end

  def edit
    @bucket = Bucket.find(params[:id])
  end

  def update
    @bucket = Bucket.find(params[:id])
    if @bucket.update(bucket_params)
      redirect_to bucket_path(@bucket)
    else
      render :edit
    end
  end

  def destroy
    @bucket = Bucket.find(params[:id])
    @bucket.destroy
    redirect_to buckets_path
  end

private

  def bucket_params
    params.require(:bucket).permit(:name, :user_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_bucket

  def index
    @lists = List.where(bucket_id:@bucket)
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = @bucket.lists.new(list_params)
    if @list.save
      redirect_to bucket_list_path(@bucket, @list)
    else
      render :new
    end
  end

  def edit
    @list = @bucket.lists.find(params[:id])
  end

  def update
    @list = @bucket.lists.find(params[:id])
    if @list.update(list_params)
      redirect_to bucket_list_path(@bucket, @list)
    else
      render :edit
    end
  end

  def destroy
    @list = @bucket.lists.find(params[:id])
    @list.destroy
    redirect_to bucket_path(@bucket)
  end

private

  def find_bucket
    @bucket = Bucket.find(params[:bucket_id])
  end

  def list_params
    params.require(:list).permit(:catergory, :location, :description, :completed, :bucket_id)
  end

end

app/controllers/staticpage_controller.rb
class StaticpageController < ApplicationController
  def index
  end
end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :birthday, :email, :password, :password_confirmation] )
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/staticpage_helper.rb
module StaticpageHelper
end

app/views/buckets/_form.html.erb
<%= simple_form_for @bucket do |f| %>
  <%= f.input :name %>
  <div class='waves-effect waves-light btn'>
  <%= f.submit :submit %>
</div>
  <% end %>

app/views/buckets/edit.html.erb
<div class="row">
  <div class="col s6 offset-s2"><h1>Edit Bucket</h1></div>
  <div class="col s6 offset-s1"><%= render(partial: 'form') %></div>
</div>

app/views/buckets/index.html.erb
<div class="row">
	 <div class="col s12 m6">
		 <div class="card">
			 <div class="card-content card-action">
				 <span class="card-title"><h2>Your Buckets</h2></span>
				 <% if @buckets.any? %>
				 <ul>
					 <% @buckets.each do |bucket| %>
					 <li class="nav">
						 <h3><%= link_to bucket.name, bucket_path(bucket) %></h3>
					 </li>
					 <% end %>
				 </ul>
				 <% else %>
				 <% end %>
			 </div>
			 <div class="card-action">
				 <a><%= link_to "Add A Bucket", new_bucket_path %> </a>
			 </div>
		 </div>
	 </div>
 </div>

app/views/buckets/new.html.erb
<div class="row">
  <div class="col s6 offset-s2"><h1>New Bucket</h1></div>
  <div class="col s6 offset-s1"><%= render(partial: 'form') %></div>
</div>

app/views/buckets/show.html.erb
<div class="row">
		 <div class="col s12 m6">
			 <div class="card">
				 <div class="card-content">
					 <span class="card-title"><h1>Ready to Fill the Bucket?</h1></span>
           <h3> <%= link_to "Enter #{@bucket.name}'s bucket", bucket_lists_path(@bucket) %> </h3>

        <%= link_to 'All Buckets', buckets_path %> |
        <%= link_to 'Edit Bucket', edit_bucket_path(@bucket) %> |
        <%= link_to 'Delete Bucket', bucket_path(@bucket), method: :delete %>
				 </div>
			 </div>
		 </div>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BucketList</title>
    <%= csrf_meta_tags %>
     <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>

  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo left">Bucket List</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to "All Buckets", buckets_path %></a></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></a></li>

      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for [@bucket, @list] do |f| %>
  <%= f.label :category %>
  <%= f.select :category, List.category %>
  <br/>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <br/>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br/>
  <%= f.check_box :completed %>
  <%= f.label :completed %>
  <br/>
  <div class='waves-effect waves-light btn'>
  <%= f.submit :submit %>
  </div>
  <% end %>

app/views/lists/edit.html.erb
<div class="row">
  <div class="col s6 offset-s2"><h1>Edit List</h1></div>
  <div class="col s6 offset-s1"><%= render(partial: 'form') %></div>
</div>

app/views/lists/index.html.erb
<div class='col-margin'>
<h1><%= @bucket.name.capitalize %> List</h1>

<% if @lists.any? %>

  <ul>
    <% @lists.each do |list| %>
    <% if list.completed? %>
      <li >
        <h5>Completed!</h5>
        <div class="completed-list collection">
        <%= list.category %>
        <h6> Location: <%= list.location %></h6>
        <h6> Description: <%= list.description %></h6>
        <div/>
        <%= link_to 'Show', bucket_list_path(@bucket, list) %>
      </li>
    <% else %>
      <h5>To Do: </h5>
      <li class='not-completed collection'>
        <%= list.category %>
        <h6> Location: <%= list.location %></h6>
        <h6> Description: <%= list.description %></h6>
        <%= link_to 'Show', bucket_list_path(@bucket, list) %>
      </li>
     <% end %>
   <% end %>
 </ul>
<% else %>
<p>Your List is Empty, that's boring.</p>
<% end %>

<%= link_to 'Create List', new_bucket_list_path(@bucket) %> |

<%= link_to 'Back to Bucket', bucket_path(@bucket) %>
</div>

app/views/lists/new.html.erb
<div class="row">
  <div class="col s6 offset-s2"><h1>New List</h1></div>
  <div class="col s6 offset-s1"><%= render(partial: 'form') %></div>
</div>

app/views/lists/show.html.erb
<h1><%= @bucket.name %> List</h1>

<% if @list.present? %>

   <ul class='collection'>
     <li class='collection-item'>
       <%= @list.category %>
       <br />
       <%= @list.location %>
       <br />
       <%= @list.description %>

     </li>
   </ul>
<% else %>
  <h3>Your List is Empty, thats boring.</h3>
<% end %>

<%= link_to 'Back to Bucket Lists', bucket_lists_path(@bucket) %> |
<%= link_to 'Edit List', edit_bucket_list_path(@bucket, @list) %> |
<%= link_to 'Delete List', bucket_list_path(@bucket, @list), method: :delete %>

app/views/staticpage/index.html.erb
<h1>Welcome <%= current_user.first_name %> to your bucket list</h1>
<a><%= link_to "Dive into your bucket", buckets_path(@bucket) %></a>